# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - mkdocs-material
        - mkdocs-include-markdown-plugin
        - mkdocs-gen-files
        - mkdocs-literate-nav
        - mkdocs-minify-plugin
        - mkdocs-section-index
        - mkdocs-git-revision-date-localized-plugin
        - mkdocstrings
        - mkdocs-redirects
        - mkdocs-glightbox
        - mike
        - pymdown-extensions
        - pygments
