# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - mkdocs~=1.6
        - mkdocs-material[imaging]~=9.4
        - mkdocs-include-markdown-plugin
        - mkdocs-gen-files
        - mkdocs-literate-nav
        - mkdocs-minify-plugin~=0.8
        - mkdocs-section-index
        - mkdocs-git-revision-date-localized-plugin~=1.2
        - mkdocstrings[python]
        - mkdocs-redirects~=1.2
        - mkdocs-glightbox~=0.4.0
        - mike~=2.1
        - pymdown-extensions~=10.9
        - pygments~=2.18
        - linkchecker~=10.4
