# This file was forcefully added to repo overriding .gitignore rule
# to demonstrate how public and secret configurations are merged.
# You should provide Dynaconf object with your own path(s) to configurations
# files.

username = 'guest'
http_password = 'guest'
